INSERT INTO `empleado_laborando`(`id_empleado`,
                                 `carne`,
                                 `nombres`,
                                 `apellidos`,
                                 `dpi`,
                                 `nit`,
                                 `fecha_nacimiento`,
                                 `profesion`,
                                 `numero_colegiado`,
                                 `colegio_profesional`,
                                 `estado_civil`,
                                 `nacionalidad`,
                                 `es_asesor`,
                                 `activo`,
                                 `es_catedratico`,
                                 `id_de_rol`)
     VALUES (NULL,
             '45345',
             'dfdsfsdf',
             'sdfsdfsdf',
             '53455',
             '345345',
             '2017-11-22',
             'sdfgsdgfg',
             '34534535',
             'dfghdfgddfg',
             'fgrfgdg',
             'dfgdfgfg',
             '1',
             '1',
             '1',
             '1');

INSERT INTO `credenciales_sistema`(`id_sistema`, `password_sistema`)
     VALUES ('1002', 'patito');